=== araceliloptru/109LMSGIProyectoLMSGI/examen/03/03/input/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="pedido">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="tractor">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="componente" type=""/>
                        <xs:element name="fechaEntrega" type="xs:date"/>
                        <xs:element name="peso" type="xs:float"/>
                        <xs:element name="numeroSerie" type="xs:string"/>
                        <xs:element name="cantidad" type="xs:int"/>
                        <xs:element name="fecha">
                            <xs:complexType>
                                <xs:sequence> 
                                <xs:element name="fechaEntrega">
                                 <!--Elemento fechaEntrega con restricciones de tipo y formato  --> 
                                 <xs:complexType>
                                 <xs:simpleContent>
                                 <xs:extension base="xs:string">
                                 <xs:attribute name="mes" default="05">
                                 <xs:simpleType>
                                 <xs:restriction>
                                 <xs:enumeration value="anio"/>
                                 <xs:enumeration value="dia"/>
                                 </xs:restriction>
                                 </xs:simpleType>
                                 </xs:attribute>
                                 </xs:extension>
                                 </xs:simpleContent>
                                 </xs:complexType>
                                </xs:element>
                                <xs:element name="fragil" type="xs:string" /> 
                                <xs:element name="peso" type="xs:string"/>
                                <xs:element name="numeroSerie" type="xs:string"/>
                                <xs:element name="kmMaximos"  type="xs:string"/>
                                <xs:element name="cantidad" type="xs:string"/>
                            </xs:sequence> <!-- end of componente sequence -->
                            <xs:attribute name="referencia" type="xs:string"/>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence> <!-- end of tractor sequence -->
                <xs:attribute name="codigoFabricante" type="xs:string"/>
            </xs:complexType>
        </xs:element>
    </xs:sequence> <!-- end of pedido sequence-->
    <xs:attribute name="idPedido" type="xs:string"/>
    <xs:attribute name="fecha" type="xs:string"/>
</xs:complexType>
</xs:element>
</xs:schema>

=== araceliloptru/109LMSGIProyectoLMSGI/examen/03/03/input/pedido.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedido idPedido="P002" fecha="2025-04-01"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pedidos.xsd" >
    <tractor codigoFabricante="F001">
        <componente referencia="CMP0000001">
            <fechaEntrega mes="04" anio="2025"/>
            <peso unidad="g">300</peso>
            <numeroSerie>SN111111111</numeroSerie>
            <kmMaximos>200000</kmMaximos>
            <cantidad>1</cantidad>
            <fecha><AAAA-MM-DD></AAAA-MM-DD></fecha>
        </componente>
        <componente referencia="CMP0000002">
            <peso unidad="g">300</peso>
            <numeroSerie>SN111111112</numeroSerie>
            <cantidad>2</cantidad>
            <fecha><AAAA-MM-DD></AAAA-MM-DD></fecha>
        </componente>
        <componente referencia="CMP0000003">
            <peso unidad="g">150</peso>
            <numeroSerie>SN111111113</numeroSerie>
            <kmMaximos>250000</kmMaximos>
            <cantidad>1</cantidad>
            <fecha><AAAA-MM-DD></AAAA-MM-DD></fecha>
        </componente>
        <componente referencia="CMP0000004">
            <peso unidad="g">300</peso>
            <numeroSerie>SN111111114</numeroSerie>
            <kmMaximos>100000</kmMaximos>
            <cantidad>4</cantidad>
            <fecha><AAAA-MM-DD></AAAA-MM-DD></fecha>
        </componente>
        <componente referencia="CMP0000005">
            <peso unidad="g">150</peso>
            <numeroSerie>SN111111115</numeroSerie>
            <kmMaximos>100000</kmMaximos>
            <cantidad>1</cantidad>
            <fecha><AAAA-MM-DD></AAAA-MM-DD></fecha>
        </componente>
    </tractor>
    <tractor codigoFabricante="F012">
        <componente referencia="CMP0000006">
            <fechaEntrega mes="05" anio="2025" dia="10"/>
            <peso unidad="kg">1</peso>
            <numeroSerie>SN222222221</numeroSerie>
            <cantidad>1</cantidad>
            <fecha><AAAA-MM-DD></AAAA-MM-DD></fecha>
        </componente>
        <componente referencia="CMP0000007">
            <fragil/>
            <peso unidad="kg">20</peso>
            <numeroSerie>SN222222222</numeroSerie>
            <kmMaximos>100000</kmMaximos>
            <cantidad>1</cantidad>
            <fecha><AAAA-MM-DD></AAAA-MM-DD></fecha>
        </componente>
        <componente referencia="CMP0000008">
            <fragil/>
            <peso unidad="kg">25</peso>
            <numeroSerie>SN222222223</numeroSerie>
            <cantidad>1</cantidad>
            <fecha><AAAA-MM-DD></AAAA-MM-DD></fecha>
        </componente>
        <componente referencia="CMP0000009">
            <fragil/>
            <peso unidad="kg">30</peso>
            <numeroSerie>SN222222224</numeroSerie>
            <cantidad>4</cantidad>
            <fecha><AAAA-MM-DD></AAAA-MM-DD></fecha>
        </componente>
        <componente referencia="CMP0000010">
            <peso unidad="g">105</peso>
            <numeroSerie>SN222222225</numeroSerie>
            <cantidad>1</cantidad>
            <fecha><AAAA-MM-DD></AAAA-MM-DD></fecha>
        </componente>
    </tractor>
</pedido>
