=== araceliloptru/109LMSGIProyectoLMSGI/u5/PRUEBAEXAMEN/01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Declaración tipos simples-->
    <xs:simpleType name="monedaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yenes"/>
            <xs:enumeration value="dolares"/>
            <xs:enumeration value="euros"/>
        </xs:restriction>
    </xs:simpleType>
 
    <xs:simpleType name="idiomaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="espanol"/>
            <xs:enumeration value="ingles"/>
        </xs:restriction>
    </xs:simpleType>
 
    <xs:simpleType name="paisType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="usa"/>
            <xs:enumeration value="mexico"/>
            <xs:enumeration value="argentina"/>
        </xs:restriction>
    </xs:simpleType>
 
    <!-- Declaración tipos complejos-->
    <xs:complexType name="bonoType">
        <xs:sequence>
            <xs:element name="valoractual">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="valor" type="xs:decimal"/>
                    </xs:sequence>
                    <xs:attribute name="moneda" type="monedaType" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="beneficio" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
 
    <xs:complexType name="futuroType">
        <xs:sequence>
            <xs:element name="elemento">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="idioma" type="idiomaType" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="beneficio" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
 
    <xs:complexType name="accionesType">
        <xs:sequence>
            <xs:element name="empresa">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="pais" type="paisType" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="beneficio" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
 
    <!-- Declaración de elementos-->
    <xs:element name="productosfinancieros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="bono" type="bonoType"/>
                            <xs:element name="futuro" type="futuroType"/>
                            <xs:element name="acciones" type="accionesType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== araceliloptru/109LMSGIProyectoLMSGI/u5/PRUEBAEXAMEN/01.xml
<?xml version="1.0" encoding="UTF-8"?>
<productosfinancieros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="01.xsd">
    <producto>
        <bono>
            <valoractual moneda="yenes">2.212</valoractual>
            <beneficio>-2.83</beneficio>
        </bono>
    </producto>
    <producto>
        <futuro>
            <elemento idioma="espanol"> Petroleo </elemento>
            <beneficio>-3.83</beneficio>
        </futuro>
    </producto>
    <producto>
        <acciones>
            <empresa pais="usa">ENRON</empresa>
            <beneficio>2.91</beneficio>
        </acciones>
    </producto>
</productosfinancieros>
